version: "3"
services:
    flaskapp:
        build: .
        ports:
          - 5000:5000
        environment: 
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db 
    db:
        image: "postgres:9.6.5"
        environment: 
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db 
          USE_POSTGRES: "True"